FROM oraclelinux:8

RUN set -ex \
    #&& yum -y module enable php:7.4 \
    && yum -y module enable php:7.2 \
    && yum -y install oracle-epel-release-el8 \
    && yum --setopt skip_missing_names_on_install=false --setopt install_weak_deps=false --nodocs -y install \
        ca-certificates curl php-fpm php-cli php-pdo php-mbstring php-mysqlnd php-gd php-json php-soap php-xml \
        fcgi msmtp \
    && rm -rf /var/cache/yum/*

RUN set -ex \
    && sed -i 's/listen.acl_users = apache,nginx/listen.acl_users =/' /etc/php-fpm.d/www.conf \
    && sed -i 's|listen = /run/php-fpm/www.sock|listen = 0.0.0.0:9000|' /etc/php-fpm.d/www.conf \
    && sed -i '/^listen.allowed_clients/c;listen.allowed_clients =' /etc/php-fpm.d/www.conf \
    && sed -i '/catch_workers_output/s/^;//' /etc/php-fpm.d/www.conf \
    && sed -i 's|;clear_env.*|clear_env = no|' /etc/php-fpm.d/www.conf \
    && sed -i 's|;pm.status_path.*|pm.status_path = /status|' /etc/php-fpm.d/www.conf \
    && sed -i 's|;ping.path.*|ping.path = /ping|' /etc/php-fpm.d/www.conf \
    && sed -i 's|;ping.response.*|ping.response = pong|' /etc/php-fpm.d/www.conf \
    #&& echo 'error_log = /proc/self/fd/1' >> /etc/php.d/custom.ini \
    && echo 'expose_php = off' > /etc/php.d/custom_php.ini \
    && mkdir -p /run/php-fpm \
    && chgrp -R 0 /run/php-fpm /var/log/php-fpm \
    && chmod -R g=u /run/php-fpm /var/log/php-fpm \
    && ln -sf /proc/self/fd/1 /var/log/php-fpm/www-slow.log \
    && ln -sf /proc/self/fd/1 /var/log/php-fpm/www-error.log \
    && ln -sf /proc/self/fd/1 /var/log/php-fpm/error.log

USER 1000:0
CMD ["/usr/sbin/php-fpm", "-F"]
STOPSIGNAL SIGQUIT
EXPOSE 9000
