FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
USER root
RUN set -ex \
    && apt-get -q update \
    && apt-get -q -y install --no-install-recommends \
        tzdata ca-certificates curl \
        php-fpm php-cli php-redis php-pdo php-mbstring php-mysqlnd php-gd \
        php-json php-soap php-xml php-curl php-imagick php-intl php-opcache \
        php-zip unzip libfcgi-bin msmtp \
    && ln -s /usr/bin/msmtp /usr/sbin/sendmail \
    && rm -rf /var/lib/apt/lists/*

RUN set -ex \
    && sed -i 's|listen = /run/php/php8.1-fpm.sock|listen = 0.0.0.0:9000|' /etc/php/8.1/fpm/pool.d/www.conf \
    #&& sed -i 's|;access.log.*|access.log = /proc/self/fd/2|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;catch_workers_output.*|catch_workers_output = yes|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;decorate_workers_output.*|decorate_workers_output = no|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;clear_env.*|clear_env = no|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;pm.status_path.*|pm.status_path = /status|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;ping.path.*|ping.path = /ping|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;ping.response.*|ping.response = pong|' /etc/php/8.1/fpm/pool.d/www.conf \
    && sed -i 's|;log_limit.*|log_limit = 8192|' /etc/php/8.1/fpm/php-fpm.conf \
    && mkdir -p /run/php \
    && chgrp -R 0 /run/php /var/lib/php/sessions \
    && chmod -R g=u /run/php /var/lib/php/sessions \
    && ln -sf /usr/sbin/php-fpm8.1 /usr/sbin/php-fpm \
    && ln -sf /proc/self/fd/2 /var/log/php8.1-fpm.log

COPY custom_php.ini /etc/php/8.1/fpm/conf.d/999-custom_php.ini
COPY msmtprc /etc/msmtprc

USER www-data:0

STOPSIGNAL SIGQUIT
ENV STOPSIGNAL QUIT
EXPOSE 9000
CMD ["/usr/sbin/php-fpm", "-F", "-O"]